---
layout: src/_includes/docs-layout.php
page_title: Redirections
docs_nav_item: redirections
---

<h2>Redirections</h2>

<p>StaticPHP supports URL redirection, allowing you to automatically redirect users from one page to another. This is particularly useful when moving or renaming pages, ensuring that old URLs continue to work seamlessly.</p>

<p><b>Note:</b> Redirections apply only to web pages. For redirects involving assets or non-HTML files, you'll need to use alternative methods.</p>

<h3>Bulk Redirects</h3>

<p>The <b>Bulk Redirects</b> feature in StaticPHP enables you to manage multiple redirects easily using a single file: <code>_bulk_redirects</code>. This file allows you to list all your redirection rules in one place, making it simple to update or add new redirects without modifying your codebase.</p>

<p>You can customise the name of this file in your build configuration by setting <code>bulk_redirects_filename</code> to your preferred filename.</p>

<h4>Format</h4>

<p>Each redirection rule should be placed on a new line. The format consists of two parts:</p>

<ol>
    <li><b>Old Path:</b> The original URL or path that needs to be redirected.</li>
    <li><b>Destination Path/URL:</b> The target URL or new path that the original URL should point to.</li>
</ol>

<p>These two parts should be separated by a <b>space</b>.</p>

<h4>Example</h4>

<p>Here's an example of how your <code>_bulk_redirects</code> file might look:</p>

<pre>
/here /there
/old.html /new.html
/about /about-us
</pre>

<p>In the example above:</p>

<ul>
    <li><code>/here</code> will be redirected to <code>/there</code>.</li>
    <li><code>/old.html</code> will be redirected to <code>/new.html</code>.
    <li><code>/about</code> will redirect to <code>/about-us</code>.</li>
</ul>

<h4>Notes:</h4>

<ul>
    <li>Ensure that paths in the old URL are relative (without domain or protocol) and use forward slashes <code>/</code>.</li>
    <li>The destination can be an absolute URL or relative path. If using an absolute URL (e.g., <code>https://example.tld/new</code>), make sure it includes the full URL structure.</li>
</ul>

<p>This system makes it easy to handle large-scale redirects in bulk, simplifying site maintenance and ensuring a smooth user experience even after restructuring or updating content.</p>

<h3>Single Redirections</h3>

<p>The <b>Single Redirections</b> feature in StaticPHP allows you to easily redirect from one page to another, either within your site or to an external URL. This is useful in cases where you want to redirect users from an outdated or temporary URL while still preserving the content of the original page in your project source files.</p>

<p>You can define the special metadata key <code>redirect</code> at the top of your page's source file. The value of <code>redirect</code> should be the target path or URL where the page should redirect. StaticPHP will process this metadata and automatically handle the redirection for you, without rendering the original page content.</p>

<h4>How It Works</h4>

<p>When StaticPHP encounters a page with a <code>redirect</code> key in the metadata, it won't output the page's regular content. Instead, it will generate a response that instructs the browser to perform a redirection to the specified URL or path.</p>

<h4>Example</h4>

<p>Let's say you have a file named <code>old.html</code> and you want to redirect users to a new page located at <code>https://example.tld/new</code>. You would add the following metadata at the top of the file:</p>

<pre>
---
redirect: https://example.tld/new
---
</pre>

<p>In this example:</p>

<ul>
    <li>The <code>redirect</code> key specifies the target URL: <code>https://example.tld/new</code>.</li>
    <li>When StaticPHP processes this file, it will <b>not render the content of <code>old.html</code></b>. Instead, it will generate an HTTP response that tells the browser to redirect to the specified URL.</li>
</ul>

<p>The user's browser will automatically follow the redirect, and they will be taken to <code>https://example.tld/new</code>.</p>

<h4>Notes:</h4>

<ul>
    <li>The <code>redirect</code> URL can be either an absolute URL (e.g., <code>https://example.tld/new</code>) or a relative URL (e.g., <code>/new</code>).</li>
    <li>This feature is ideal for temporary redirects or handling legacy URLs.</li>
</ul>

<h3>How Does the Redirection Work?</h3>

<p>StaticPHP creates a simple HTML file at the path you specified. This file contains a meta refresh tag that automatically redirects the user to the new destination. This is a well-established technique supported by almost all modern browsers.</p>

<p>The HTML file generated by StaticPHP will include the following structure:</p>

<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
    &lt;head&gt;
        &lt;meta http-equiv="refresh" content="0; url='https://example.tld/new'" /&gt;
        &lt;title&gt;Redirecting...&lt;/title&gt;
    &lt;/head&gt;
    
    &lt;body&gt;
        &lt;p&gt;If you are not redirected, &lt;a href="https://example.tld/new"&gt;click here&lt;/a&gt;.&lt;/p&gt;
    &lt;/body&gt;
&lt;/html&gt;
</pre>

<p>In this example, the <code>&lt;meta&gt;</code> tag tells the browser to wait 0 seconds before redirecting to the new URL (<code>https://example.tld/new</code>). If, for any reason, the redirection does not work, users can click the provided link to reach the new destination.</p>

<h4>Custom Redirection Template</h4>

<p>You can specify your own HTML structure for the redirection page by creating a file in the root of your source directory called <code>_redirection_template.html</code>. If this file exists, StaticPHP will use its contents when generating the redirection page, giving you full control over the design, layout, and even the timing of the redirection.</p>

<p>You can customise the name of this file in your build configuration by setting <code>redirection_template_filename</code> to your preferred filename.</p>

<p>This customization allows you to adjust the timing of the redirection, should you want to delay it for any reason (e.g., to display a message to users before they are redirected).</p>

<p>The following placeholders are available for use in your custom redirection template:</p>

<ul>
    <li><b>$newDestination</b>: The target URL where the user will be redirected.</li>
    <li><b>$oldPath</b>: The path from which the user is being redirected.</li>
</ul>

<h5>Example</h5>

<p>Here's an example of a custom <code>_redirection_template.html</code> file:</p>

<pre>
&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
    &lt;head&gt;
        &lt;meta charset="UTF-8"&gt;
        &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
        &lt;meta http-equiv="refresh" content="5; url='$newDestination'" /&gt;

        &lt;title&gt;Redirecting...&lt;/title&gt;
    &lt;/head&gt;

    &lt;body&gt;
        &lt;h1&gt;Redirecting...&lt;/h1&gt;
        &lt;p&gt;You are about to be redirected from &lt;b&gt;$oldPath&lt;/b&gt; to &lt;b&gt;$newDestination&lt;/b&gt;.&lt;/p&gt;
        &lt;p&gt;If you are not redirected within 5 seconds, &lt;a href="$newDestination"&gt;click here&lt;/a&gt;.&lt;/p&gt;
    &lt;/body&gt;
&lt;/html&gt;
</pre>

<p>In this example:</p>

<ul>
    <li>The <code>$newDestination</code> placeholder is replaced with the URL where the user is being redirected.</li>
    <li>The <code>$oldPath</code> placeholder is replaced with the path the user is coming from.</li>
    <li>The redirection is delayed for <b>5 seconds</b>, as specified by the <code>content="5; url='$newDestination'"</code> attribute in the <code>&lt;meta&gt;</code> tag. You can adjust the number <code>5</code> to any number of seconds you want for the delay, or set it to <code>0</code> for no delay.</li>
</ul>

<h3>Why Meta Refresh?</h3>

<p>The <code>&lt;meta http-equiv="refresh"&gt;</code> tag has been used for automatic redirection for many years and is supported by nearly all browsers. While this method is generally reliable, StaticPHP ensures that if the redirect fails, a clickable link is provided as a backup.</p>
